// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afgulmwbgtktnurbknka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmZ3VsbXdiZ3RrdG51cmJrbmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNzAwMzAsImV4cCI6MjA2NjY0NjAzMH0.29rAmuIwHyP8Xj2Fw7ZkyuSdvEonQTx_A4BHdd1UBfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);